FROM php:5.6

# git
RUN apt update && apt install -y git unzip

# install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# config
COPY ./conf/php.ini /usr/local/etc/php/php.ini

# bash start
ENTRYPOINT [ "/bin/bash" ]