version: '3'
services:
    fuel:
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ./workspace:/var/www/html/fuel
        ports:
            - "8080:80"
    workspace:
        build:
            context: .
            dockerfile: Dockerfile-Workspace
        volumes: 
            - ./workspace/:/workspace
        working_dir: /workspace
